<link rel="stylesheet" href="css/style.css" type="text/css" media="all" />
<table class="header" width="100%">
<tr>
	<td><h1 style="margin-left:20px;"><a href="index.php">XploreBoy.Tk</a></h1></td>
	<td align="right"><form method="get" action="./search.php">
		<input type="text" name="query" placeholder=" enter title or artist" required="required" pattern=".{3,}">
		<input type="submit" value="Search">
		</form>
	</td>
</tr>
</table>
<br /><br />
<p align="center">BookMark @Mysite.Com<br />Here at mysite You Can Get Latest English, Punjabi, Bollywood, Haryanvi And All Other Language Music On The Go, Just Browse And Listen Your Favourite Music</p>
<br /><br />